version: '3.7'

services:
  bot-db:
    container_name: bot-db
    build:
      context: .
      dockerfile: Dockerfile_mysql
    ports:
      - "3306:3306"
  bot-api:
    container_name: bot-api
    build:
      context: .
      dockerfile: Dockerfile_api
    command:
      - java
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      - "-XX:ParallelGCThreads=8"
      - "-jar"
      - "bot-0.0.1-SNAPSHOT.jar"
    links:
      - bot-db:database
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024M
